services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ootiebot
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  ootiebot:
    image: ${IMAGE_REPOSITORY}:${IMAGE_TAG:-master}
    restart: unless-stopped
    environment:
      DB_PATH: /opt/STORAGE
      RESOURCE_PATH: /opt/resources

      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_BOT_USERID: ${DISCORD_BOT_USERID}
      GUILDID_LIST: ${GUILDID_LIST}

      POSTGRES_JDBC_URL: ${POSTGRES_JDBC_URL}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
    depends_on:
      - db

    volumes:
      - ${HOST_OOTIE_REPO_DIR}/src/main/resources:/opt/resources:ro

    stop_grace_period: 10m

networks:
  ootie:
    name: ootie