services:
  ootiebot:
    image: ${IMAGE_REPOSITORY}:${IMAGE_TAG:-master}
    restart: unless-stopped
    environment:
      AWS_KEY: ${AWS_KEY}
      AWS_SECRET: ${AWS_SECRET}

      DB_PATH: /opt/STORAGE
      RESOURCE_PATH: /opt/resources

      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_BOT_USERID: ${DISCORD_BOT_USERID}
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
      GUILDID_LIST: ${GUILDID_LIST}

      REPO_DISPATCH_TOKEN: ${REPO_DISPATCH_TOKEN}
      TI4_ULTIMATE_STATISTICS_API_KEY: ${TI4_ULTIMATE_STATISTICS_API_KEY}
      MANAGEMENT_ENDPOINTS_ACTUATOR_API_KEY: ${MANAGEMENT_ENDPOINTS_ACTUATOR_API_KEY}

      POSTGRES_JDBC_URL: ${POSTGRES_JDBC_URL}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

      DISCORD_REDIRECT_URI: ${DISCORD_REDIRECT_URI}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}

      ROLLBAR_ACCESS_TOKEN: ${ROLLBAR_ACCESS_TOKEN}
      ROLLBAR_ENVIRONMENT: ${ROLLBAR_ENVIRONMENT:-production}
      ROLLBAR_CODE_VERSION: ${ROLLBAR_CODE_VERSION:-unknown}

    volumes:
      - ${HOST_TI4_SAVES_DIR}:/opt/STORAGE
      - ${HOST_TI4_REPO_DIR}/src/main/resources:/opt/resources:ro

    stop_grace_period: 10m

networks:
  ootie:
    name: ootie